apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: calculator
    tier: backend