pipeline {
  agent any
  
  environment { 
      MINIKUBE_URL = credentials('minikube-url')
  }
    
  stages {
    stage ('Clone Repository') {
      steps {
        git branch: 'main', url: "https://github.com/Gabriely-get/calculator-k8s-deployment.git"
      }
    }
    stage('Install kubectl in Jenkins') {
      steps {
        withKubeConfig([credentialsId: 'jenkins-account', 
            serverUrl: "$MINIKUBE_URL", 
            contextName: 'minkube',
            clusterName: 'minikube',
            ]) {
              
          sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.26.3/bin/linux/amd64/kubectl"'  
          sh 'chmod u+x ./kubectl'
        }   
      }
    }
    stage('Create calculator deployment and service') {
      steps {
        withKubeConfig([credentialsId: 'jenkins-account-secret', 
              serverUrl: "$MINIKUBE_URL", 
              contextName: 'minkube',
              clusterName: 'minikube',
              ]) {
                
          sh './kubectl create -f kubernetes/calculator-deployment.yml'
          sh './kubectl create -f kubernetes/calculator-service.yml'
        }
      }
    }
  }

}